services:
  backend:
    image: booking_backend
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_USER: ${DB_USER}
      DATABASE_NAME: ${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
      - "51212:51212"
    env_file: ".env"
    command: npm run start:dev
    volumes:
      - ./backend:/app/back
      - /app/back/node_modules

  frontend:
    image: booking_frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      VITE_BACKEND_HOST: http://localhost:3000
    volumes:
      - ./frontend:/app/front
      - /app/front/node_modules
    depends_on:
      backend:
        condition: service_started
    env_file: ".env"
    command: npm run dev

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: booking_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  db_data:
  redis_data:
